name: 10.15 SDK

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
            config: macos-11.txt 
          - os: macos-12
            config: macos-12.txt 
          - os: macos-13
            config: macos-13.txt 
          - os: macos-14
            config: macos-14.txt 

    runs-on: ${{ matrix.os }}

    steps:
      - id: package
        name: package the sdk
        run: |
          mkdir -p xcode
          export config=${{ matrix.config }}
          bash build.sh
          echo "release_tag=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
          
      - name: Upload release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: xcode/*.tar.xz
          tag: ${{ steps.package.outputs.release_tag }}
          file_glob: true
          overwrite: true
