name: package macOS SDKs

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            config: macos-13.txt 
          - os: macos-14
            config: macos-14.txt
          - os: macos-15
            config: macos-15.txt

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - id: package
        name: package the sdk
        run: |
          ls -lah
          mkdir -p xcode
          export config=${{ matrix.config }}
          bash build.sh
          echo "release_tag=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
          
      - name: Upload release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: xcode/*.tar.xz
          tag: ${{ steps.package.outputs.release_tag }}
          file_glob: true
          overwrite: true
