name: iPhoneOS-SDK

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - run: |
          mkdir -p xcode
          wget https://github.com/growtopiajaw/MacOSX-SDK/raw/master/build.sh
          bash build.sh
          
      - name: Upload release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: xcode/*.tar
          tag: v1.0
          file_glob: true
          overwrite: true
