name: 11 SDK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
      - run: |
          mkdir -p xcode
          wget https://github.com/growtopiajaw/MacOSX-SDK/raw/main/build-2.sh
          wget https://github.com/growtopiajaw/MacOSX-SDK/raw/main/macos-11.txt
          bash build-2.sh
          
      - name: Upload release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: xcode/*.tar
          tag: v1.0
          file_glob: true
          overwrite: true
